bot:
  prefix: "BOT_PREFIX_HERE"
  locale: "BOT_LOCALE_HERE"
  token: "BOT_TOKEN_HERE"
database:
  name: "MONGO_DB_NAME_HERE"
  cluster: "MONGO_CLUSTER_URL_HERE"
cachet:
  enabled: false
  url: "CACHET_URL_HERE"
  key: "CACHET_KEY_HERE"
sentry:
  enabled: false
  dsn: "SENTRY_DSN_HERE"
developers:
  - "USER_ID_HERE"