bot:
  prefix: "BOT_PREFIX_HERE"
  token: "BOT_TOKEN_HERE"
database:
  name: "MONGO_DB_NAME_HERE"
  cluster: "MONGO_CLUSTER_URL_HERE"
sentry:
  enabled: false
  dsn: "SENTRY_DSN_HERE"
developers:
  - "USER_ID_HERE"